name: Generate Cyber Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # 每天自动更新
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: AlanZhaoxdd
          outputs: |
            dist/cyber-snake.svg
          color_snake: "#00FFD1"                     # 霓虹青绿
          color_dots: "#6B21A8,#312E81"              # 紫色调像素背景
          mask: pixel                                 # 像素风格动画
          palette: github-dark

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
